apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-api
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: course-api
  template:
    metadata:
      labels:
        app: course-api
    spec:
      containers:
      - name: course-api
        image: us-central1-docker.pkg.dev/nitin-project-gcp/sims/course-api:latest
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 3030
        readinessProbe:
          httpGet:
            port: web
            path: /api/v1/courses
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: CLUSTER_NAME
            valueFrom:
              configMapKeyRef:
                key: CLUSTER_NAME        
                name: cluster-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"